import os
from typing import Any

from supabase import Client, create_client


# This SQL is only kept as a reference.
# It is not executed automatically by this Python file.
SETUP_SQL = """
create extension if not exists vector
with schema extensions;

create table if not exists public.document_chunks (
    id bigint generated by default as identity primary key,
    document_id text not null,
    source_name text not null,
    page_number text not null,
    chunk_index integer not null,
    content text not null,
    embedding extensions.vector(1536) not null,
    created_at timestamptz not null default now(),

    constraint unique_document_chunk
        unique (document_id, chunk_index)
);

drop function if exists public.match_document_chunks(
    extensions.vector,
    integer,
    double precision,
    text
);

create or replace function public.match_document_chunks(
    query_embedding extensions.vector(1536),
    match_count integer default 5,
    match_threshold double precision default 0.5,
    filter_document_id text default null
)
returns table (
    document_id text,
    source_name text,
    page_number text,
    chunk_index integer,
    content text,
    similarity double precision
)
language sql
stable
as $$
    select
        dc.document_id,
        dc.source_name,
        dc.page_number,
        dc.chunk_index,
        dc.content,
        (
            1 - (dc.embedding <=> query_embedding)
        )::double precision as similarity
    from public.document_chunks as dc
    where
        (
            filter_document_id is null
            or dc.document_id = filter_document_id
        )
        and (
            1 - (dc.embedding <=> query_embedding)
        ) >= match_threshold
    order by dc.embedding <=> query_embedding
    limit greatest(match_count, 1);
$$;
"""


class VectorStore:
    EMBEDDING_DIMENSION = 1536

    def __init__(self) -> None:
        url = os.getenv("SUPABASE_URL", "").strip().rstrip("/")
        api_key = os.getenv("SUPABASE_API_KEY", "").strip()

        if not url or not api_key:
            raise ValueError(
                "SUPABASE_URL and SUPABASE_API_KEY must be set in your .env file."
            )

        if not url.startswith("https://"):
            raise ValueError(
                "SUPABASE_URL must start with https://"
            )

        if "/rest/v1" in url:
            raise ValueError(
                "SUPABASE_URL must only contain the project URL. "
                "Remove /rest/v1 from the URL."
            )

        self.client: Client = create_client(url, api_key)
        self.table_name = "document_chunks"
        self.match_function = "match_document_chunks"

    def test_connection(self) -> bool:
        """
        Test whether Supabase and the document_chunks table are accessible.
        """
        try:
            response = (
                self.client
                .table(self.table_name)
                .select("id")
                .limit(1)
                .execute()
            )

            print("Supabase connection successful.")
            print("Data:", response.data)

            return True

        except Exception as error:
            raise RuntimeError(
                f"Supabase connection failed: {error}"
            ) from error

    def add_chunks(self, chunks: list[dict[str, Any]]) -> int:
        """
        Insert document chunks into Supabase.

        Existing chunks with the same document_id and chunk_index
        are updated because the table has a unique constraint on
        those two columns.
        """
        if not chunks:
            raise ValueError("No document chunks were provided.")

        rows = []

        for chunk in chunks:
            self._validate_chunk(chunk)

            rows.append(
                {
                    "document_id": str(chunk["document_id"]),
                    "source_name": str(chunk["source_name"]),
                    "page_number": str(chunk["page_number"]),
                    "chunk_index": int(chunk["chunk_index"]),
                    "content": str(chunk["content"]),
                    "embedding": chunk["embedding"],
                }
            )

        try:
            batch_size = 50

            for start in range(0, len(rows), batch_size):
                batch = rows[start:start + batch_size]

                (
                    self.client
                    .table(self.table_name)
                    .upsert(
                        batch,
                        on_conflict="document_id,chunk_index",
                    )
                    .execute()
                )

            return len(rows)

        except Exception as error:
            raise RuntimeError(
                f"Failed to store document chunks in Supabase: {error}"
            ) from error

    def search(
        self,
        query_embedding: list[float],
        top_k: int = 5,
        document_id: str | None = None,
    ) -> list[dict[str, Any]]:
        """
        Search Supabase pgvector for chunks similar to the query embedding.
        """
        self._validate_embedding(query_embedding)

        if top_k < 1:
            raise ValueError("top_k must be at least 1.")

        match_threshold = float(
            os.getenv("MATCH_THRESHOLD", "0.5")
        )

        parameters = {
            "query_embedding": query_embedding,
            "match_count": int(top_k),
            "match_threshold": match_threshold,
            "filter_document_id": document_id,
        }

        try:
            response = (
                self.client
                .rpc(
                    self.match_function,
                    parameters,
                )
                .execute()
            )

            return response.data or []

        except Exception as error:
            raise RuntimeError(
                f"Supabase vector search failed: {error}"
            ) from error

    def delete_document(self, document_id: str) -> int:
        """
        Delete all chunks belonging to one document.
        """
        if not document_id:
            raise ValueError("document_id cannot be empty.")

        try:
            response = (
                self.client
                .table(self.table_name)
                .delete()
                .eq("document_id", document_id)
                .execute()
            )

            return len(response.data or [])

        except Exception as error:
            raise RuntimeError(
                f"Failed to delete document chunks: {error}"
            ) from error

    def _validate_chunk(self, chunk: dict[str, Any]) -> None:
        """
        Validate the fields required for inserting a chunk.
        """
        required_fields = [
            "document_id",
            "source_name",
            "page_number",
            "chunk_index",
            "content",
            "embedding",
        ]

        missing_fields = [
            field
            for field in required_fields
            if field not in chunk
        ]

        if missing_fields:
            raise ValueError(
                "Chunk is missing required fields: "
                + ", ".join(missing_fields)
            )

        if not str(chunk["document_id"]).strip():
            raise ValueError("document_id cannot be empty.")

        if not str(chunk["source_name"]).strip():
            raise ValueError("source_name cannot be empty.")

        if not str(chunk["content"]).strip():
            raise ValueError("Chunk content cannot be empty.")

        self._validate_embedding(chunk["embedding"])

    def _validate_embedding(
        self,
        embedding: list[float],
    ) -> None:
        """
        Ensure the embedding matches vector(1536).
        """
        if not isinstance(embedding, list):
            raise ValueError(
                "Embedding must be a Python list."
            )

        if len(embedding) != self.EMBEDDING_DIMENSION:
            raise ValueError(
                f"Embedding must contain exactly "
                f"{self.EMBEDDING_DIMENSION} values, "
                f"but received {len(embedding)}."
            )

        if not all(
            isinstance(value, (int, float))
            for value in embedding
        ):
            raise ValueError(
                "Every embedding value must be a number."
            )


def print_setup_sql() -> None:
    """
    Print the SQL setup script for manual execution
    in the Supabase SQL Editor.
    """
    print(SETUP_SQL)


if __name__ == "__main__":
    store = VectorStore()
    store.test_connection()