import os

from supabase import create_client


SETUP_SQL = """
create extension if not exists vector;

create table if not exists document_chunks (
    id bigint generated by default as identity primary key,
    document_id text not null,
    source_name text not null,
    page_number text not null,
    chunk_index integer not null,
    content text not null,
    embedding vector(1536) not null,
    created_at timestamptz default now()
);

create or replace function match_document_chunks(
    query_embedding vector(1536),
    match_count integer default 5,
    match_threshold double precision default 0.5,
    filter_document_id text default null
)
returns table (
    document_id text,
    source_name text,
    page_number text,
    chunk_index integer,
    content text,
    similarity double precision
)
language sql stable
as $$
    select
        dc.document_id,
        dc.source_name,
        dc.page_number,
        dc.chunk_index,
        dc.content,
        1 - (dc.embedding <=> query_embedding) as similarity
    from document_chunks dc
    where
        (filter_document_id is null or dc.document_id = filter_document_id)
        and 1 - (dc.embedding <=> query_embedding) >= match_threshold
    order by dc.embedding <=> query_embedding
    limit match_count;
$$;
"""


class VectorStore:
    def __init__(self):
        url = os.getenv("SUPABASE_URL")
        api_key = os.getenv("SUPABASE_API_KEY")
        if not url or not api_key:
            raise ValueError("SUPABASE_URL and SUPABASE_API_KEY must be set in .env.")

        self.client = create_client(url, api_key)
        self.table_name = "document_chunks"
        self.match_function = "match_document_chunks"

    def add_chunks(self, chunks):
        rows = [
            {
                "document_id": chunk["document_id"],
                "source_name": chunk["source_name"],
                "page_number": str(chunk["page_number"]),
                "chunk_index": chunk["chunk_index"],
                "content": chunk["content"],
                "embedding": chunk["embedding"],
            }
            for chunk in chunks
        ]

        try:
            for start in range(0, len(rows), 50):
                self.client.table(self.table_name).insert(rows[start : start + 50]).execute()
        except Exception:
            self.delete_document(chunks[0]["document_id"])
            raise

    def search(self, query_embedding, top_k=5, document_id=None):
        response = self.client.rpc(
            self.match_function,
            {
                "query_embedding": query_embedding,
                "match_count": top_k,
                "match_threshold": float(os.getenv("MATCH_THRESHOLD", "0.5")),
                "filter_document_id": document_id,
            },
        ).execute()
        return response.data or []

    def delete_document(self, document_id):
        self.client.table(self.table_name).delete().eq("document_id", document_id).execute()


def print_setup_sql():
    print(SETUP_SQL)


if __name__ == "__main__":
    print_setup_sql()
